language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: FtRWSfSCsab6W2DaHW1TMMz1/J3vtrzCf8pIgyEmCxsttNwWpblYMh1lCLnUFvUBUOhVg1jqmt7Kxxho8IQkfwYs9whl89WMlGkq0oao7Zhce1hnok/3LowN+hut+Y7EqmPvwOu+qLx/1HbXHosYRI66c2OZwrpILIn2iY6I0PG35T70nzv6bU80GlLuW+YIUNCOxARElrEeCi5TKQPe7rJ0WkjWZnZq28Z+R0vnR030nDrq34aCQYeL9f5rupE9PAGxtqyATFYe6LsU6l7sI/lE4BjwovEEiZXoAtCR2hg8hGPE5cfMOpHlnlkE+g7R8HGzWhyDUdRb6NsciyzTxG0nkM+HJ4r5jiL621jQHDhq7ssLyme8UPcFUxxPsgWPk+JoUvuwImAxRX2+u5CHTP2nrckoAGn3kKMMt5AjE2IU+5a4/m5J9aN41NHRuFA2oP7PqXY5xS1uaX+/LXib1hmiBG9pWAmu7blIDG2DZOIbcuPoXESEScZyAFfo7fzF2o48a7jcn3QNSVXoE4SWUPX/odjEXKtz/WHSAADXJPBSsXCJiYCL+SIBIT/Il2RB9+ADlK4QilPBXe6Eheu8iwfqWl+0jtl9yKpgW3AqKxGHa+buyf61iSl8zKgikVh2prNIRhgs8ps4XEZ+Rj+oRzDWt07Sd2Q3EWaBDJiw9Uk=
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
