language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: xl+pfyZP3La4M6e0VBZkWsr0Co3Aotm/yejvRjxBS6iQzVBPtBdRC2+wr0sL1TqVkD+62CTHHXRrCXfDOw6AArHtiVf9BerfbEQ1wiAkDnQZActKp4DRRPH7KhA5VVRojH7EOgIWvsbRQQsJAmmhG4OczBhoMwAy/arvhQ1RIWO/A0wmcZKFXoZ9low0vma4BEyvd5KovdJan6RGpb74NgGFxSpcCy9j6wMMr0cw6ibs15atRqMNyhh2Iw+4wObXYLL8WkBnkFyOZ2EpATu1d22zUROS72if4+B0JioDqhNA/JNAUnCBIyourNsNbluhK1mBbdU5I/lNThTIfQuNIk5V4eMDEz0AmxWdXNxr/JXIsmgDWsHMnDlT/4H+o7uum3/tfMd9RM5WrMToH/H6W28QcQ+4jgJzAQHnMupEDSrd0f02HfA1FGZ3omGKmDR+TMHDAzuz3W+q32XNa7qnhWa8Jv8T3cv0f+QYhX/uqK2UUcW3wFkpnUdHar9Ul9btPkpI4bFgQOiXtMYYd7HkIIZFes/1G1v+6cAHx2WbZ7sROJZ1LA7Govj8X1CclsEFP9IT6dm5OuSEMWKqft9Je1xR+Nb2Po8zQwpsMZDQYSD+rNpFhYLh1121+lr167Z8KMqkzh03layDo2JBid9Z8DLrw7R5owmy6MwU65h9ZuI=
  on:
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
