language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: G19o7c2n2tASSOIlPfF9Qpj9RwpfJENZj2ha+JDtrM+bRECMERejnZikfHRl80wUKZnjcl7JlbfcrndN3z/G4nwUyxCPzNAjpNFNskmBlE6Y9FjAZqgYjR3cjp3w4rBNwJcpOecT9JbImoB3v8UCQO7pWVt4T2yAeRkuU5jKfqFnzvXInD4CkFehwoT634qnX82vG4xdDRXkCsAyZLTztzH+ZFiqyeiQEu9QfJv9ucbTF/i254UeVKgVwMrB4VOwQvC6Z9l5EcEzwY53DzHr/xYt+v+x6/Y1GjZXi/PiLlao0my4Chw/dyTK4WXdXUG4z9CMRVGbh+bLVBpbPXNbXN6o/dMD8N/fC4nrnB8Hc8nhtD5F5aCUFiGc3gL2IQ7YW0RNF5yjsiu0KCK27Cn0wy5t30o/0xLTXW1RmcN51QjFVo3DzZd9/mCjFZN5dFIx7b6APf5d+SLxEGjq1a6T45uSiyi+oBWRBu1kIuS1tZfx5td4Ml3cJmzWQ0fKkiGH76gfaz0oxvXcAdrtXf3+pVyYiElhcirLUGlFiT1ZNhhiFI1kkzIb5GmwikNAMvOxXsL0+OLep0kFlnu5jMBG27U3zjOGS0mmZjqhEXP2rA/em5cnKFDV2iU3pE+RUwIE2O3ohV0EAfnGd72Aje+DqDxdz/28w55zhL32CE9J/FA=
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
