language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: u3yUsQdhQLgWwMfEtABDSsokdtj97XgLLtgdCctVh3T4E2cIR7VRJyP/WnhdpltIWJ2rHKyej9MeEaOR1orjy4+gNYfApjEcP5osV3KXnMuPgFlfMansfMYYHYuhfy6dRTEc4QpGkg1KZ425uPYnuUDBTMNCeSAcGb33mIMRTOvQeNhGo7fO8LVeYoaBBIGrxk4p9LlOWB596u9Wgum3N0kmkUklDXC4JXzJH+0gyU7TpFM1HVDux82Jooej/nOo2/KHeu87E+6XG9IQf/5E55K7Oi92gtgHt5ydN+OFg0zHLC/vaZb8RRHxcfzHeIF/MCQYjRx7hWEB/BFOYSnoR4Wgn1L2q2n2yUW+vnZUFRpzmgSuwiDnt4928wm37KP9Vspg1kIRpxM4NrFvnDBHNrfSFr0c1UHEIyBryjPfnHQx/gx1ehmB9mBUnH2XEh/+w6uJ3aatB3MXiwp3+tiG08kF7YZIxgMuexqsiq6As+/GhMFwBh5p+RMrUf5LhBZL7a41ZhzRqf3P1b8OessT8tYJG5GAJZ3ACG4DuaRmWAEKy6oUDd6JQF7DtTmzqk1sOWYE06EmKcVueZ3WXtGLnnl+BGBkGY6TSYW7lQtCUGTrn+EbRyzPYBxyXDK9+3gUrzrcWevOgdSrHiPn2Rc4ba1SWEzVkXIFQHvVbRzjsYw=
    email: r3850365@gmail.com@gmail.com
  on:
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
