language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: Qyh3Q26lEYpdybvjxaMggb0h+st/a6hImb0nVlKNJZlFVAJnDRF9svnS8Nqk7AIEQ6kJu+eXyuhWBoJIingT4tft1zPSjEhXFZZUr3HAmDc5R3TxqigHgnWoNNAStC3UO8+5L25y9kv9y3sWGb/0BxYRWfT4QxH4ZBw02fTfKKiGnhZ8MSAJOT5fQGErTdTgIdea7HaNGzSdbhNVN9Zd4cdi4uOI6Eyx29/dbh6jC1HTTDIeCvxR0McxZpVa0OK7kALhxmg9h7zxrPGQeCEQiztaq14LiyojbYWeqQSoewdHYC9yUh7rK/HEKAbvsLkxUTFFVZfeXrflXhDNUDMRr2kfo5C+21uTbRc9TRjBRaNsSmyJ5J1woGPfbk3duVyBFQXj8WKUa+MI1rZ1SPO/7UpBfJ8LJKeTl0JQ40+n9llQbcyP25D0qk9weISF0owoCsE9C1/p4vXGCxZGoyB4r0x1ji6iiWYyHVTmGVBAJ0cmDXu6hokos7iNtLOxaHg4cQxSpYWznlxPnbsz1TKi15p19rmBKdsrGKdt3iW8yhUDehM2SJq7FjLLkXAPUBddvxhtlXCoK2uLKq/Sf6AKK1JLWk1/UpNJxoo9qtto1bP+zQgitcN4hfjl7Tlmt+t8x+XCRGPQh1z9MH02YJH3+4Lqx/8UqrRlOFOVIMA/ASI=
  email: r3850365@gmail.com@gmail.com
  on:
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
