language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
  email: r3850365@gmail.com@gmail.com
  on:
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
env:
  global:
    secure: dRSQVvEOUnlMbcbyKJj8TccNgP84RbjeqYSmrbwSvT9L8TC66mH01762ccarn7q8axcmF5AvH/qnVm8VbxHl2gI/f8scGg7tb4ttLki21jU0pNJspwEfdTFPS8Rb+QQM3WO2LepYWZrKhE7N2xi1X5NQcDnZAWAecwCBik2aMlkQSdGThvEbqzup9+J8pCnBtgLY/9nrZNx/WiuwYiL5s+Eqld1tqWPNsfyzW0iQ4GHLN8LiBf0kWB3fO6W0FEXHy7MNg2wCWFYeo87PiaoU84lJY4ZekIURl8gFz5o4ocKK+aMxGZjqD4LGP7zDjDIcgHlZRjz4uqcyDwMNPC8jnR98CuT6xjT0Ey1n0wG0uteEBUtxBhtbH/A6YaO/akHqDUJLMam/CVAm6njVYDFCx5HXyFtnFNYja6KpSBVBecvccQJ1M39jixNWm8jMgN7O+A81JNGjboOB6sotVepX32YKUbFm4OzEchbUqsrne8W1PHPu3n6A+T3zS01InP1YnHkpfcrLxfP71lRzn3H6IZc6nRYoUZTaoN7Wmf2nP2SN4MSIr0PODknz1HyeH269Qct4Vu+3qXoNqHawVNG47vvqUDQTxI9tadNAHPKbQ89XvR2lkglDF7UH7SKuSOV5NlRXgLAOeTVPxpQOvG10Ny1OYRVAdP2yaRkEfpfVIKA=
