language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: bIQCdieG6SXEzbk4p47l4QBTU1Zcmtqj7TilXZ5G8WNkeBKtrE06hO1Jtr7VSIDMRvg/BLVmvzhxmKNjmBsXSeRjGLdjM1AFgtbmKxVBDDPN5s82/LRT5t4We/D7NKHmHqeTS/bsZdYKJgDcltc9pN1EwE29yQO8hQSSfIszbxAvAW208DpaFFKlXr+WWnHiNgi7oKWNTiGsQj9aCSDhgtCd9cJGcs4sjMTepmQjCP6dJFbm0JLzlFkk65reEKfPiSj8e5vdYKn83sxFxhNGTtE5OEuLIJmZXz27Nyj/5sPYIRP7bp1BwQ0lcKJKrDsmv4FxdT3f39tGqCt/DkAmOFlADmkMYwxX1VuVsqykXsQwyOKqXcH1PY3yugpv318aKtRf5E0D/UTDuv33mZR+eLFZspcQpaKd1NNZEgNS/JCNzkGL+2wl/4IQ7feCljsTNlK8apXFEnuSLvjAERe/i9ebRm7GaZJ6iwYi4xioUKv4bdeY0vKEuwawG2sRDWucJqlvvk429/WJwZojKLTwLjshYFaXlydXz34NpePgpRjlW1Na3/eEct64rXF3LRUU3tVeHdUoFYGUQnzXr/XFZnO3/Mln6fvJig28FtctUxzG3LhCN/4pjsSHFWXmMXe7xSj9FFaYoPNfECwpWXsnCt4EzdO+mvpFHQ43ebJyP0c=
  email: r3850365@gmail.com@gmail.com
  on:
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
