language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: U3ouI9BhxXlzLrZyuEUjJcYGnUIfAYYXmq9Fkj7Z+96MDaw1yTnoKYsaCMTz0l2F8ocPQ8Z79qUSyxdJt+TvEpX3WhNIBRfAD3Z+X8qIV3sBEyGVb8hpKsVS4JiYdoz2uV1093AUq6hCtP1PvkazFt+IyjFt+fBOderMxBCAyH4ZgF/4CtKioAWcQSCc1ziR25Lp4sLHiPIAPFUr1h+BM7FMwiTt4L2hTuOlBC0BWlSTIpTKJPQNm3Opm0FHEn4/+c/zQbogwvu1/NffO36ZcKfPVhcGHXNKRaoMXpPuzLcmiSciLLw9chksns6P02DCq0904FXc2TU5xIKkJA4UvY1DKP4i15t5okWFTIDCsvQ+tQyI2Q68Lr/GoFCKunKU5mTQD8KIoxmL5gwuz3MIlr1DayKxG+7eAObcJQfZ2YG3z983ZVvMMGesCUl/dfAg5EtMB6epmgPyXeNcQCNvAtC6m6xf3GmLWqWIMPJ5wxhMzWJxf55H2UZZUTqje76UMnxsbtMYvH0aclZzvqh2HESs/K2jEsY2qCKCZABBBAIhf1gVJ+W75iVdkdD2GEr/2xVylcPEMSFOY+5hm2UVGBRrrqISh6e6LoUPqG0Sq0yYZ/KaMnDlqviIXC9cvX9rYKWYPSCu1fdHGc6jTlEjCppOW+dsQu74LkrgFM0FT9w=
  on:
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
