language: node.js
node_js:
- 8.11.1
script: "./setup.sh"
sudo: required
dist: trusty
addons:
  chrome: stable
install: npm install
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
scripts:
- ng e2e
- ng build --aot -prod
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  app: rms-sparklines-styleguide
  api_key:
    secure: mKCaz8m+YlDB2/DybMdUlqhiwlRuTnjOK9sC1KDw8skIusQdW+VJMf6Gw1WuRCSIOqspY9tEkaciu34YqNYcEI0oxFCXqdYDA0G+5XL3486o/nRkNc1IlU57uwzZGYt72ieZpkTHUdkzP9had1Q2X9dIcv/dv80RDAQJMUo1KmHuzKXUZ4HDwczMHCk23HiAUkuRLwegrhtv+wUmoIdtKkaIncFrPdr5lhU6UujkIxiK0U8Yd8tBEjf9D50f2LdFMXO60I+Ic+TkHMepiVQIFWPw5TQ0fcKOsmPxBFzcvJWzufZTKqMI96Z+gJ/0nYOt12jisZfxkSIrIutUyb3SwJUxinC7L90v4DtIIhXZzbsj7HW0qa+JK4w34Pq0bJoRWWaEQjHjUalQGhA3j5TgG23VS27C+zyi0ebCBMV1ibDHvqjIyCYWhkmp44MCbvhoDP1osvYAsnqbz7bucMDEoebnmHGXF8ygWPa5Irr8/tYad3RE39TweCxcLLx0VCuSfhRHlOiSHC2LKUY0AK3WVrK6QKmg50VRFhbQpmwcdOyC5zYFcr+Ni+bupd2iz+1CuFs1adoiZA59K4bygM0Tj5EwBJxNZVLO7A8FjfnUd4E/sMszB0zNw36yktutcSPoK0ytighDUyc+1yMw7tLUijUlLJ//4K8VwTbaYV4GHqg=
    repo: RodrigoMattosoSilveira/rms-sparklines-styleguide
branches:
  only:
  - master
